### ISSUE TITLE
Müşteri oluşturma hk.

### ISSUE THREAD

**Issue by dgokhan** [yagizzcann/Edvido.Integrations.Parasut#3]
Selamlar, sisteme yeni müşteri kaydı yaptığımda sürekli isim null değeri hatası alıyorum (Name is a required property for InlineResponse2002Attributes and cannot be null)

Deneme yaptığım CreateContact;
                var createCust = provider.Client.Contacts.CreateContact(new Model.ContactForm
                {
                    Data = new Model.CompanyIdcontactsData
                    {
                        Attributes = new Model.InlineResponse2002Attributes
                        {
                            AccountType = Model.InlineResponse2002Attributes.AccountTypeEnum.Customer,
                            Address = "46",
                            City = "İzmir",
                            ContactType = Model.InlineResponse2002Attributes.ContactTypeEnum.Person,
                            District = "XXXXXXX",
                            Email = "info@gokhandogru.net",
                            Name = "XXXX XXXX",
                            Phone = "XXXXXXXX",
                            ShortName = "XXXXXX"
                        },
                        Type = Model.CompanyIdcontactsData.TypeEnum.Contacts,
                    }
                }, companyId);
                
Veriyi doldurup gönderdiğimde ContactForm ctorda data sürekli null geliyor. Acaba yanlış veri mi gönderiyorum?                
![image](https://user-images.githubusercontent.com/30188543/115151209-90beb580-a074-11eb-9203-a4b978862ba4.png)

**Comment by yagizzcann** [comment]
Merhaba, 

new Model.InlineResponse2002Attributes(“xxx”,””,””)

Seklinde nesneyi kurucu metodu kullanarak yaratırsanız hata almamanız gerekiyor.
